# Generated by Django 3.2.20 on 2024-06-01 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('timestamp', models.DateTimeField(verbose_name='Дата и время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поисковой запрос',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.query')),
            ],
            options={
                'verbose_name': 'Краткий пересказ',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.query')),
            ],
            options={
                'verbose_name': 'Результат поискового запроса',
            },
        ),
    ]
